#!/bin/bash

while read -r line; do
        if [[ "$line" =~ 'Situation' ]]; then
		echo Relationship Category >> relat.col
        elif [[ "$line" =~ 'cousin'|'sister'|'couple'|'grand' ]]; then
                echo Family >> relat.col
	elif [[ "$line" =~ 'colleague'|'worker' ]]; then
		echo Work >> relat.col
	elif [[ "$line" =~ 'friend' ]]; then
		echo Friend >> relat.col
	elif [[ "$line" =~ 'informal' ]]; then
		echo Other informal >> relat.col
        else
                echo Other >> relat.col
        fi
done < situations.col

